<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '\Helvetica',
    'bold' => $fontDir . '\Helvetica-Bold',
    'italic' => $fontDir . '\Helvetica-Oblique',
    'bold_italic' => $fontDir . '\Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '\Times-Roman',
    'bold' => $fontDir . '\Times-Bold',
    'italic' => $fontDir . '\Times-Italic',
    'bold_italic' => $fontDir . '\Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '\Times-Roman',
    'bold' => $fontDir . '\Times-Bold',
    'italic' => $fontDir . '\Times-Italic',
    'bold_italic' => $fontDir . '\Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '\Courier',
    'bold' => $fontDir . '\Courier-Bold',
    'italic' => $fontDir . '\Courier-Oblique',
    'bold_italic' => $fontDir . '\Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '\Helvetica',
    'bold' => $fontDir . '\Helvetica-Bold',
    'italic' => $fontDir . '\Helvetica-Oblique',
    'bold_italic' => $fontDir . '\Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '\ZapfDingbats',
    'bold' => $fontDir . '\ZapfDingbats',
    'italic' => $fontDir . '\ZapfDingbats',
    'bold_italic' => $fontDir . '\ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/symbol',
    'bold' => $fontDir . '/symbol',
    'italic' => $fontDir . '/symbol',
    'bold_italic' => $fontDir . '/symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '\Times-Roman',
    'bold' => $fontDir . '\Times-Bold',
    'italic' => $fontDir . '\Times-Italic',
    'bold_italic' => $fontDir . '\Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '\Courier',
    'bold' => $fontDir . '\Courier-Bold',
    'italic' => $fontDir . '\Courier-Oblique',
    'bold_italic' => $fontDir . '\Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '\Courier',
    'bold' => $fontDir . '\Courier-Bold',
    'italic' => $fontDir . '\Courier-Oblique',
    'bold_italic' => $fontDir . '\Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '\DejaVuSans-Bold',
    'bold_italic' => $fontDir . '\DejaVuSans-BoldOblique',
    'italic' => $fontDir . '\DejaVuSans-Oblique',
    'normal' => $fontDir . '\DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '\DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '\DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '\DejaVuSansMono-Oblique',
    'normal' => $fontDir . '\DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '\DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '\DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '\DejaVuSerif-Italic',
    'normal' => $fontDir . '\DejaVuSerif',
  ),
  'nanum gothic' => array(
    'normal' => $fontDir . '\adf85360f83b054cc290bf2ac692dcdf',
  ),
  'calibri light' => array(
    'normal' => $fontDir . '/CalibriL',
    'bold' => $fontDir . '/CalibriL',
    'italic' => $fontDir . '/CalibriLI',
    'bold_italic' => $fontDir . '/CalibriL',
  ),
  'candara' => array(
    'normal' => $fontDir . '/Candara',
    'bold' => $fontDir . '/Candarab',
    'italic' => $fontDir . '/Candarai',
    'bold_italic' => $fontDir . '/Candaraz',
  ),
  'gabriola' => array(
    'normal' => $fontDir . '/Gabriola',
    'bold' => $fontDir . '/Gabriola',
    'italic' => $fontDir . '/Gabriola',
    'bold_italic' => $fontDir . '/Gabriola',
  ),
  'khmer ui' => array(
    'normal' => $fontDir . '/KhmerUIb',
    'bold' => $fontDir . '/KhmerUIb',
    'italic' => $fontDir . '/KhmerUIb',
    'bold_italic' => $fontDir . '/KhmerUIb',
  ),
  'lao ui' => array(
    'normal' => $fontDir . '/LaoUIb',
    'bold' => $fontDir . '/LaoUIb',
    'italic' => $fontDir . '/LaoUIb',
    'bold_italic' => $fontDir . '/LaoUIb',
  ),
  'shonar bangla' => array(
    'normal' => $fontDir . '/Shonar',
    'bold' => $fontDir . '/Shonarb',
    'italic' => $fontDir . '/Shonar',
    'bold_italic' => $fontDir . '/Shonar',
  ),
  'vani' => array(
    'normal' => $fontDir . '/Vani',
    'bold' => $fontDir . '/Vanib',
    'italic' => $fontDir . '/Vani',
    'bold_italic' => $fontDir . '/Vani',
  ),
  '안상수2006굵은' => array(
    'normal' => $fontDir . '/ahn_b',
    'bold' => $fontDir . '/ahn_b',
    'italic' => $fontDir . '/ahn_b',
    'bold_italic' => $fontDir . '/ahn_b',
  ),
  '안상수2006가는' => array(
    'normal' => $fontDir . '/ahn_l',
    'bold' => $fontDir . '/ahn_l',
    'italic' => $fontDir . '/ahn_l',
    'bold_italic' => $fontDir . '/ahn_l',
  ),
  '안상수2006중간' => array(
    'normal' => $fontDir . '/ahn_m',
    'bold' => $fontDir . '/ahn_m',
    'italic' => $fontDir . '/ahn_m',
    'bold_italic' => $fontDir . '/ahn_m',
  ),
  'aharoni' => array(
    'normal' => $fontDir . '/ahronbd',
    'bold' => $fontDir . '/ahronbd',
    'italic' => $fontDir . '/ahronbd',
    'bold_italic' => $fontDir . '/ahronbd',
  ),
  'andalus' => array(
    'normal' => $fontDir . '/andlso',
    'bold' => $fontDir . '/andlso',
    'italic' => $fontDir . '/andlso',
    'bold_italic' => $fontDir . '/andlso',
  ),
  'angsana new' => array(
    'normal' => $fontDir . '/angsaz',
    'bold' => $fontDir . '/angsaz',
    'italic' => $fontDir . '/angsaz',
    'bold_italic' => $fontDir . '/angsaz',
  ),
  'angsanaupc' => array(
    'normal' => $fontDir . '/angsauz',
    'bold' => $fontDir . '/angsauz',
    'italic' => $fontDir . '/angsauz',
    'bold_italic' => $fontDir . '/angsauz',
  ),
  'aparajita' => array(
    'normal' => $fontDir . '/aparaj',
    'bold' => $fontDir . '/aparajb',
    'italic' => $fontDir . '/aparaji',
    'bold_italic' => $fontDir . '/aparajbi',
  ),
  'arabic typesetting' => array(
    'normal' => $fontDir . '/arabtype',
    'bold' => $fontDir . '/arabtype',
    'italic' => $fontDir . '/arabtype',
    'bold_italic' => $fontDir . '/arabtype',
  ),
  'arial' => array(
    'normal' => $fontDir . '/ariali',
    'bold' => $fontDir . '/ariali',
    'italic' => $fontDir . '/ariali',
    'bold_italic' => $fontDir . '/ariali',
  ),
  'arial black' => array(
    'normal' => $fontDir . '/ariblk',
    'bold' => $fontDir . '/ariblk',
    'italic' => $fontDir . '/ariblk',
    'bold_italic' => $fontDir . '/ariblk',
  ),
  'browallia new' => array(
    'normal' => $fontDir . '/browa',
    'bold' => $fontDir . '/browab',
    'italic' => $fontDir . '/browai',
    'bold_italic' => $fontDir . '/browaz',
  ),
  'browalliaupc' => array(
    'normal' => $fontDir . '/browau',
    'bold' => $fontDir . '/browaub',
    'italic' => $fontDir . '/browaui',
    'bold_italic' => $fontDir . '/browauz',
  ),
  'calibri' => array(
    'normal' => $fontDir . '/calibri',
    'bold' => $fontDir . '/calibrib',
    'italic' => $fontDir . '/calibrii',
    'bold_italic' => $fontDir . '/calibriz',
  ),
  'comic sans ms' => array(
    'normal' => $fontDir . '/comicbd',
    'bold' => $fontDir . '/comicbd',
    'italic' => $fontDir . '/comicbd',
    'bold_italic' => $fontDir . '/comicbd',
  ),
  'consolas' => array(
    'normal' => $fontDir . '/consola',
    'bold' => $fontDir . '/consolab',
    'italic' => $fontDir . '/consolai',
    'bold_italic' => $fontDir . '/consolaz',
  ),
  'constantia' => array(
    'normal' => $fontDir . '/constan',
    'bold' => $fontDir . '/constanb',
    'italic' => $fontDir . '/constani',
    'bold_italic' => $fontDir . '/constanz',
  ),
  'corbel' => array(
    'normal' => $fontDir . '/corbel',
    'bold' => $fontDir . '/corbelb',
    'italic' => $fontDir . '/corbeli',
    'bold_italic' => $fontDir . '/corbelz',
  ),
  'cordia new' => array(
    'normal' => $fontDir . '/cordia',
    'bold' => $fontDir . '/cordiab',
    'italic' => $fontDir . '/cordiai',
    'bold_italic' => $fontDir . '/cordiaz',
  ),
  'cordiaupc' => array(
    'normal' => $fontDir . '/cordiau',
    'bold' => $fontDir . '/cordiaub',
    'italic' => $fontDir . '/cordiaui',
    'bold_italic' => $fontDir . '/cordiauz',
  ),
  'courier new' => array(
    'normal' => $fontDir . '/couri',
    'bold' => $fontDir . '/couri',
    'italic' => $fontDir . '/couri',
    'bold_italic' => $fontDir . '/couri',
  ),
  'daunpenh' => array(
    'normal' => $fontDir . '/daunpenh',
    'bold' => $fontDir . '/daunpenh',
    'italic' => $fontDir . '/daunpenh',
    'bold_italic' => $fontDir . '/daunpenh',
  ),
  'david' => array(
    'normal' => $fontDir . '/david',
    'bold' => $fontDir . '/davidbd',
    'italic' => $fontDir . '/david',
    'bold_italic' => $fontDir . '/david',
  ),
  'dokchampa' => array(
    'normal' => $fontDir . '/dokchamp',
    'bold' => $fontDir . '/dokchamp',
    'italic' => $fontDir . '/dokchamp',
    'bold_italic' => $fontDir . '/dokchamp',
  ),
  'ebrima' => array(
    'normal' => $fontDir . '/ebrimabd',
    'bold' => $fontDir . '/ebrimabd',
    'italic' => $fontDir . '/ebrimabd',
    'bold_italic' => $fontDir . '/ebrimabd',
  ),
  'estrangelo edessa' => array(
    'normal' => $fontDir . '/estre',
    'bold' => $fontDir . '/estre',
    'italic' => $fontDir . '/estre',
    'bold_italic' => $fontDir . '/estre',
  ),
  'euphemia' => array(
    'normal' => $fontDir . '/euphemia',
    'bold' => $fontDir . '/euphemia',
    'italic' => $fontDir . '/euphemia',
    'bold_italic' => $fontDir . '/euphemia',
  ),
  'franklin gothic medium' => array(
    'normal' => $fontDir . '/framdit',
    'bold' => $fontDir . '/framdit',
    'italic' => $fontDir . '/framdit',
    'bold_italic' => $fontDir . '/framdit',
  ),
  'frankruehl' => array(
    'normal' => $fontDir . '/frank',
    'bold' => $fontDir . '/frank',
    'italic' => $fontDir . '/frank',
    'bold_italic' => $fontDir . '/frank',
  ),
  'gautami' => array(
    'normal' => $fontDir . '/gautami',
    'bold' => $fontDir . '/gautamib',
    'italic' => $fontDir . '/gautami',
    'bold_italic' => $fontDir . '/gautami',
  ),
  'georgia' => array(
    'normal' => $fontDir . '/georgiaz',
    'bold' => $fontDir . '/georgiaz',
    'italic' => $fontDir . '/georgiaz',
    'bold_italic' => $fontDir . '/georgiaz',
  ),
  'gisha' => array(
    'normal' => $fontDir . '/gishabd',
    'bold' => $fontDir . '/gishabd',
    'italic' => $fontDir . '/gishabd',
    'bold_italic' => $fontDir . '/gishabd',
  ),
  'microsoft himalaya' => array(
    'normal' => $fontDir . '/himalaya',
    'bold' => $fontDir . '/himalaya',
    'italic' => $fontDir . '/himalaya',
    'bold_italic' => $fontDir . '/himalaya',
  ),
  'impact' => array(
    'normal' => $fontDir . '/impact',
    'bold' => $fontDir . '/impact',
    'italic' => $fontDir . '/impact',
    'bold_italic' => $fontDir . '/impact',
  ),
  'iskoola pota' => array(
    'normal' => $fontDir . '/iskpota',
    'bold' => $fontDir . '/iskpotab',
    'italic' => $fontDir . '/iskpota',
    'bold_italic' => $fontDir . '/iskpota',
  ),
  'dfkai-sb' => array(
    'normal' => $fontDir . '/kaiu',
    'bold' => $fontDir . '/kaiu',
    'italic' => $fontDir . '/kaiu',
    'bold_italic' => $fontDir . '/kaiu',
  ),
  'kalinga' => array(
    'normal' => $fontDir . '/kalinga',
    'bold' => $fontDir . '/kalingab',
    'italic' => $fontDir . '/kalinga',
    'bold_italic' => $fontDir . '/kalinga',
  ),
  'kartika' => array(
    'normal' => $fontDir . '/kartika',
    'bold' => $fontDir . '/kartikab',
    'italic' => $fontDir . '/kartika',
    'bold_italic' => $fontDir . '/kartika',
  ),
  'kokila' => array(
    'normal' => $fontDir . '/kokila',
    'bold' => $fontDir . '/kokilab',
    'italic' => $fontDir . '/kokilai',
    'bold_italic' => $fontDir . '/kokilabi',
  ),
  'lucida sans unicode' => array(
    'normal' => $fontDir . '/l_10646',
    'bold' => $fontDir . '/l_10646',
    'italic' => $fontDir . '/l_10646',
    'bold_italic' => $fontDir . '/l_10646',
  ),
  'latha' => array(
    'normal' => $fontDir . '/latha',
    'bold' => $fontDir . '/lathab',
    'italic' => $fontDir . '/latha',
    'bold_italic' => $fontDir . '/latha',
  ),
  'leelawadee' => array(
    'normal' => $fontDir . '/leelawdb',
    'bold' => $fontDir . '/leelawdb',
    'italic' => $fontDir . '/leelawdb',
    'bold_italic' => $fontDir . '/leelawdb',
  ),
  'lucida console' => array(
    'normal' => $fontDir . '/lucon',
    'bold' => $fontDir . '/lucon',
    'italic' => $fontDir . '/lucon',
    'bold_italic' => $fontDir . '/lucon',
  ),
  'levenim mt' => array(
    'normal' => $fontDir . '/lvnm',
    'bold' => $fontDir . '/lvnmbd',
    'italic' => $fontDir . '/lvnm',
    'bold_italic' => $fontDir . '/lvnm',
  ),
  'sakkal majalla' => array(
    'normal' => $fontDir . '/majallab',
    'bold' => $fontDir . '/majallab',
    'italic' => $fontDir . '/majallab',
    'bold_italic' => $fontDir . '/majallab',
  ),
  '맑은 고딕' => array(
    'normal' => $fontDir . '/malgun_0',
    'bold' => $fontDir . '/malgunbd_0',
    'italic' => $fontDir . '/malgun_0',
    'bold_italic' => $fontDir . '/malgun_0',
  ),
  'mangal' => array(
    'normal' => $fontDir . '/mangal',
    'bold' => $fontDir . '/mangalb',
    'italic' => $fontDir . '/mangal',
    'bold_italic' => $fontDir . '/mangal',
  ),
  'marlett' => array(
    'normal' => $fontDir . '/marlett',
    'bold' => $fontDir . '/marlett',
    'italic' => $fontDir . '/marlett',
    'bold_italic' => $fontDir . '/marlett',
  ),
  'microsoft sans serif' => array(
    'normal' => $fontDir . '/micross',
    'bold' => $fontDir . '/micross',
    'italic' => $fontDir . '/micross',
    'bold_italic' => $fontDir . '/micross',
  ),
  'mongolian baiti' => array(
    'normal' => $fontDir . '/monbaiti',
    'bold' => $fontDir . '/monbaiti',
    'italic' => $fontDir . '/monbaiti',
    'bold_italic' => $fontDir . '/monbaiti',
  ),
  'moolboran' => array(
    'normal' => $fontDir . '/moolbor',
    'bold' => $fontDir . '/moolbor',
    'italic' => $fontDir . '/moolbor',
    'bold_italic' => $fontDir . '/moolbor',
  ),
  'miriam' => array(
    'normal' => $fontDir . '/mriam',
    'bold' => $fontDir . '/mriam',
    'italic' => $fontDir . '/mriam',
    'bold_italic' => $fontDir . '/mriam',
  ),
  'miriam fixed' => array(
    'normal' => $fontDir . '/mriamc',
    'bold' => $fontDir . '/mriamc',
    'italic' => $fontDir . '/mriamc',
    'bold_italic' => $fontDir . '/mriamc',
  ),
  '微軟正黑體' => array(
    'normal' => $fontDir . '/msjhbd',
    'bold' => $fontDir . '/msjhbd',
    'italic' => $fontDir . '/msjhbd',
    'bold_italic' => $fontDir . '/msjhbd',
  ),
  'microsoft uighur' => array(
    'normal' => $fontDir . '/msuighur',
    'bold' => $fontDir . '/msuighur',
    'italic' => $fontDir . '/msuighur',
    'bold_italic' => $fontDir . '/msuighur',
  ),
  '微软雅黑' => array(
    'normal' => $fontDir . '/msyhbd',
    'bold' => $fontDir . '/msyhbd',
    'italic' => $fontDir . '/msyhbd',
    'bold_italic' => $fontDir . '/msyhbd',
  ),
  'microsoft yi baiti' => array(
    'normal' => $fontDir . '/msyi',
    'bold' => $fontDir . '/msyi',
    'italic' => $fontDir . '/msyi',
    'bold_italic' => $fontDir . '/msyi',
  ),
  'mv boli' => array(
    'normal' => $fontDir . '/mvboli',
    'bold' => $fontDir . '/mvboli',
    'italic' => $fontDir . '/mvboli',
    'bold_italic' => $fontDir . '/mvboli',
  ),
  'narkisim' => array(
    'normal' => $fontDir . '/nrkis',
    'bold' => $fontDir . '/nrkis',
    'italic' => $fontDir . '/nrkis',
    'bold_italic' => $fontDir . '/nrkis',
  ),
  'microsoft new tai lue' => array(
    'normal' => $fontDir . '/ntailu',
    'bold' => $fontDir . '/ntailub',
    'italic' => $fontDir . '/ntailu',
    'bold_italic' => $fontDir . '/ntailu',
  ),
  'nyala' => array(
    'normal' => $fontDir . '/nyala',
    'bold' => $fontDir . '/nyala',
    'italic' => $fontDir . '/nyala',
    'bold_italic' => $fontDir . '/nyala',
  ),
  'palatino linotype' => array(
    'normal' => $fontDir . '/palai',
    'bold' => $fontDir . '/palai',
    'italic' => $fontDir . '/palai',
    'bold_italic' => $fontDir . '/palai',
  ),
  'microsoft phagspa' => array(
    'normal' => $fontDir . '/phagspa',
    'bold' => $fontDir . '/phagspab',
    'italic' => $fontDir . '/phagspa',
    'bold_italic' => $fontDir . '/phagspa',
  ),
  'plantagenet cherokee' => array(
    'normal' => $fontDir . '/plantc',
    'bold' => $fontDir . '/plantc',
    'italic' => $fontDir . '/plantc',
    'bold_italic' => $fontDir . '/plantc',
  ),
  'raavi' => array(
    'normal' => $fontDir . '/raavi',
    'bold' => $fontDir . '/raavib',
    'italic' => $fontDir . '/raavi',
    'bold_italic' => $fontDir . '/raavi',
  ),
  'rod' => array(
    'normal' => $fontDir . '/rod',
    'bold' => $fontDir . '/rod',
    'italic' => $fontDir . '/rod',
    'bold_italic' => $fontDir . '/rod',
  ),
  'segoe print' => array(
    'normal' => $fontDir . '/segoepr',
    'bold' => $fontDir . '/segoeprb',
    'italic' => $fontDir . '/segoepr',
    'bold_italic' => $fontDir . '/segoepr',
  ),
  'segoe script' => array(
    'normal' => $fontDir . '/segoesc',
    'bold' => $fontDir . '/segoescb',
    'italic' => $fontDir . '/segoesc',
    'bold_italic' => $fontDir . '/segoesc',
  ),
  'segoe ui' => array(
    'normal' => $fontDir . '/segoeuiz',
    'bold' => $fontDir . '/segoeuiz',
    'italic' => $fontDir . '/segoeuiz',
    'bold_italic' => $fontDir . '/segoeuiz',
  ),
  'segoe ui light' => array(
    'normal' => $fontDir . '/segoeuil',
    'bold' => $fontDir . '/segoeuil',
    'italic' => $fontDir . '/segoeuil',
    'bold_italic' => $fontDir . '/segoeuil',
  ),
  'segoe ui semibold' => array(
    'normal' => $fontDir . '/seguisb',
    'bold' => $fontDir . '/seguisb',
    'italic' => $fontDir . '/seguisb',
    'bold_italic' => $fontDir . '/seguisb',
  ),
  'segoe ui symbol' => array(
    'normal' => $fontDir . '/seguisym',
    'bold' => $fontDir . '/seguisym',
    'italic' => $fontDir . '/seguisym',
    'bold_italic' => $fontDir . '/seguisym',
  ),
  'shruti' => array(
    'normal' => $fontDir . '/shruti',
    'bold' => $fontDir . '/shrutib',
    'italic' => $fontDir . '/shruti',
    'bold_italic' => $fontDir . '/shruti',
  ),
  '仿宋' => array(
    'normal' => $fontDir . '/simfang',
    'bold' => $fontDir . '/simfang',
    'italic' => $fontDir . '/simfang',
    'bold_italic' => $fontDir . '/simfang',
  ),
  '黑体' => array(
    'normal' => $fontDir . '/simhei',
    'bold' => $fontDir . '/simhei',
    'italic' => $fontDir . '/simhei',
    'bold_italic' => $fontDir . '/simhei',
  ),
  '楷体' => array(
    'normal' => $fontDir . '/simkai',
    'bold' => $fontDir . '/simkai',
    'italic' => $fontDir . '/simkai',
    'bold_italic' => $fontDir . '/simkai',
  ),
  'simplified arabic' => array(
    'normal' => $fontDir . '/simpo',
    'bold' => $fontDir . '/simpbdo',
    'italic' => $fontDir . '/simpo',
    'bold_italic' => $fontDir . '/simpo',
  ),
  'simplified arabic fixed' => array(
    'normal' => $fontDir . '/simpfxo',
    'bold' => $fontDir . '/simpfxo',
    'italic' => $fontDir . '/simpfxo',
    'bold_italic' => $fontDir . '/simpfxo',
  ),
  'simsun-extb' => array(
    'normal' => $fontDir . '/simsunb',
    'bold' => $fontDir . '/simsunb',
    'italic' => $fontDir . '/simsunb',
    'bold_italic' => $fontDir . '/simsunb',
  ),
  'sylfaen' => array(
    'normal' => $fontDir . '/sylfaen',
    'bold' => $fontDir . '/sylfaen',
    'italic' => $fontDir . '/sylfaen',
    'bold_italic' => $fontDir . '/sylfaen',
  ),
  'tahoma' => array(
    'normal' => $fontDir . '/tahomabd',
    'bold' => $fontDir . '/tahomabd',
    'italic' => $fontDir . '/tahomabd',
    'bold_italic' => $fontDir . '/tahomabd',
  ),
  'microsoft tai le' => array(
    'normal' => $fontDir . '/taile',
    'bold' => $fontDir . '/taileb',
    'italic' => $fontDir . '/taile',
    'bold_italic' => $fontDir . '/taile',
  ),
  'times new roman' => array(
    'normal' => $fontDir . '/timesi',
    'bold' => $fontDir . '/timesi',
    'italic' => $fontDir . '/timesi',
    'bold_italic' => $fontDir . '/timesi',
  ),
  'traditional arabic' => array(
    'normal' => $fontDir . '/trado',
    'bold' => $fontDir . '/tradbdo',
    'italic' => $fontDir . '/trado',
    'bold_italic' => $fontDir . '/trado',
  ),
  'trebuchet ms' => array(
    'normal' => $fontDir . '/trebucit',
    'bold' => $fontDir . '/trebucit',
    'italic' => $fontDir . '/trebucit',
    'bold_italic' => $fontDir . '/trebucit',
  ),
  'tunga' => array(
    'normal' => $fontDir . '/tunga',
    'bold' => $fontDir . '/tungab',
    'italic' => $fontDir . '/tunga',
    'bold_italic' => $fontDir . '/tunga',
  ),
  'dilleniaupc' => array(
    'normal' => $fontDir . '/upcdl',
    'bold' => $fontDir . '/upcdl',
    'italic' => $fontDir . '/upcdl',
    'bold_italic' => $fontDir . '/upcdl',
  ),
  'eucrosiaupc' => array(
    'normal' => $fontDir . '/upcel',
    'bold' => $fontDir . '/upcel',
    'italic' => $fontDir . '/upcel',
    'bold_italic' => $fontDir . '/upcel',
  ),
  'freesiaupc' => array(
    'normal' => $fontDir . '/upcfl',
    'bold' => $fontDir . '/upcfb',
    'italic' => $fontDir . '/upcfi',
    'bold_italic' => $fontDir . '/upcfbi',
  ),
  'irisupc' => array(
    'normal' => $fontDir . '/upcil',
    'bold' => $fontDir . '/upcib',
    'italic' => $fontDir . '/upcii',
    'bold_italic' => $fontDir . '/upcibi',
  ),
  'jasmineupc' => array(
    'normal' => $fontDir . '/upcjl',
    'bold' => $fontDir . '/upcjb',
    'italic' => $fontDir . '/upcji',
    'bold_italic' => $fontDir . '/upcjbi',
  ),
  'kodchiangupc' => array(
    'normal' => $fontDir . '/upckl',
    'bold' => $fontDir . '/upckb',
    'italic' => $fontDir . '/upcki',
    'bold_italic' => $fontDir . '/upckbi',
  ),
  'lilyupc' => array(
    'normal' => $fontDir . '/upcll',
    'bold' => $fontDir . '/upclb',
    'italic' => $fontDir . '/upcli',
    'bold_italic' => $fontDir . '/upclbi',
  ),
  'utsaah' => array(
    'normal' => $fontDir . '/utsaah',
    'bold' => $fontDir . '/utsaahb',
    'italic' => $fontDir . '/utsaahi',
    'bold_italic' => $fontDir . '/utsaahbi',
  ),
  'verdana' => array(
    'normal' => $fontDir . '/verdanaz',
    'bold' => $fontDir . '/verdanaz',
    'italic' => $fontDir . '/verdanaz',
    'bold_italic' => $fontDir . '/verdanaz',
  ),
  'vijaya' => array(
    'normal' => $fontDir . '/vijaya',
    'bold' => $fontDir . '/vijayab',
    'italic' => $fontDir . '/vijaya',
    'bold_italic' => $fontDir . '/vijaya',
  ),
  'vrinda' => array(
    'normal' => $fontDir . '/vrinda',
    'bold' => $fontDir . '/vrindab',
    'italic' => $fontDir . '/vrinda',
    'bold_italic' => $fontDir . '/vrinda',
  ),
  'webdings' => array(
    'normal' => $fontDir . '/webdings',
    'bold' => $fontDir . '/webdings',
    'italic' => $fontDir . '/webdings',
    'bold_italic' => $fontDir . '/webdings',
  ),
  'wingdings' => array(
    'normal' => $fontDir . '/wingding',
    'bold' => $fontDir . '/wingding',
    'italic' => $fontDir . '/wingding',
    'bold_italic' => $fontDir . '/wingding',
  ),
  '나눔고딕' => array(
    'normal' => $fontDir . '/NanumGothic',
    'bold' => $fontDir . '/NanumGothic',
    'italic' => $fontDir . '/NanumGothic',
    'bold_italic' => $fontDir . '/NanumGothic',
  ),
) ?>